FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src


COPY . .

RUN dotnet publish "backend/src/PMS.Host/PMS.Host.csproj" -c Release -o /publish

FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /App

COPY --from=build /publish .

ENTRYPOINT ["dotnet", "PMS.Host.dll"]